#module install + buiild
FROM node:20 as module-install-stage

WORKDIR /app
COPY . /app/
RUN npm install

#build stage
FROM node:20 as build-stage

WORKDIR /app
COPY --from=module-install-stage /app/ /app
RUN npm run build

#serve
FROM node:20
COPY --from=build-stage /app/dist/ /app/dist
RUN npm install -g serve

EXPOSE 3002

#start app
CMD serve -s /app/dist -l 3002